---
title: "Project Milestone"
author: "Chris Onesti"
date: "March 30, 2019"
output: html_document
---
##Project Milestone

##Presidential and Senate Twitter Activity: Trump's First 9 Months in Office

This was a great twitter sentiment analysis with very clear visuals.  One question I initially had was what to make of the fact that Trump has more positive and negative language in his tweets than the others, but this was well explained in the description.  One critique I have is specifically on the Republicans positivity sentiment analysis and the Democrats/Independents as well, which is that the x axis is not very well defined.  There are too many names and it is difficult to read.  Also the first and last names are conjoined and the first and last entries on the x axis are not formatted correctly with capitalization.  This might be a data cleaning issue.

## NHL Stats in Correlation to Goals Scored in 2017-2018 NHL Season

Again, a very straightforward and well-put design, which allows users to immediately draw insights.  Essentially the project displays many correlations.  I'm interested in knowing why the maker decided to label player names at the expense of showing just smaller dots.  This would have allowed for multiple stats to be shown on eone page.  Also, I think that from a design perspective, one can replace the team selection buttons with a dropdown menu since there are so many of them.  